### ISSUE TITLE
关于上一年和下一年

### ISSUE THREAD

**Issue by fhmob** [wenzhixin/bootstrap-monthpicker#2]
您好，我在案例中看到，input点击后可以选择上下一年，但是span上绑定后没有上下一年的按钮？
我使用id来操作，也没有效果。
文档也没看出个所以然，冒昧提问

**Comment by wenzhixin** [comment]
span 是因为加了 `from: '2013-05'` 和 `to: '2013-11'` 的属性，所以没有上下年的按钮。

**Comment by wenzhixin** [comment]
关闭这个问题
